import { getPermissionsFromCookie } from '@/lib/cookie'

export const PERMISSION_CODES = {
  USER_READ: 'USER_READ',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_RESTORE: 'USER_RESTORE',
  USER_ACTIVATE: 'USER_ACTIVATE',
  USER_RESET_PASSWORD: 'USER_RESET_PASSWORD',
  USER_SELF_READ: 'USER_SELF_READ',
  USER_SELF_UPDATE_PROFILE: 'USER_SELF_UPDATE_PROFILE',
  USER_SELF_CHANGE_PASSWORD: 'USER_SELF_CHANGE_PASSWORD',

  PAYMENT_READ: 'PAYMENT_READ',
  PAYMENT_CREATE: 'PAYMENT_CREATE',
  PAYMENT_APPROVE_LEVEL_1: 'PAYMENT_APPROVE_LEVEL_1',
  PAYMENT_APPROVE_LEVEL_2: 'PAYMENT_APPROVE_LEVEL_2',
  PAYMENT_APPROVE_FINAL: 'PAYMENT_APPROVE_FINAL',
  PAYMENT_UPLOAD_BANK_NOTE: 'PAYMENT_UPLOAD_BANK_NOTE',

  WAREHOUSE_INBOUND_READ: 'WAREHOUSE_INBOUND_READ',
  WAREHOUSE_INBOUND_CREATE: 'WAREHOUSE_INBOUND_CREATE',
  WAREHOUSE_INBOUND_UPDATE: 'WAREHOUSE_INBOUND_UPDATE',
  WAREHOUSE_INBOUND_APPROVE_LEVEL_1: 'WAREHOUSE_INBOUND_APPROVE_LEVEL_1',
  WAREHOUSE_INBOUND_APPROVE_LEVEL_2: 'WAREHOUSE_INBOUND_APPROVE_LEVEL_2',
  WAREHOUSE_INBOUND_APPROVE_FINAL: 'WAREHOUSE_INBOUND_APPROVE_FINAL',

  WAREHOUSE_OUTBOUND_READ: 'WAREHOUSE_OUTBOUND_READ',
  WAREHOUSE_OUTBOUND_CREATE: 'WAREHOUSE_OUTBOUND_CREATE',
  WAREHOUSE_OUTBOUND_UPDATE: 'WAREHOUSE_OUTBOUND_UPDATE',
  WAREHOUSE_OUTBOUND_APPROVE_LEVEL_1: 'WAREHOUSE_OUTBOUND_APPROVE_LEVEL_1',
  WAREHOUSE_OUTBOUND_APPROVE_LEVEL_2: 'WAREHOUSE_OUTBOUND_APPROVE_LEVEL_2',
  WAREHOUSE_OUTBOUND_APPROVE_FINAL: 'WAREHOUSE_OUTBOUND_APPROVE_FINAL',

  WAREHOUSE_INVENTORY_READ: 'WAREHOUSE_INVENTORY_READ',
} as const

export const USER_MANAGEMENT_PERMISSIONS = [
  PERMISSION_CODES.USER_READ,
  PERMISSION_CODES.USER_CREATE,
  PERMISSION_CODES.USER_UPDATE,
  PERMISSION_CODES.USER_DELETE,
  PERMISSION_CODES.USER_RESTORE,
  PERMISSION_CODES.USER_ACTIVATE,
  PERMISSION_CODES.USER_RESET_PASSWORD,
]

export const USER_SELF_PERMISSIONS = [
  PERMISSION_CODES.USER_SELF_READ,
  PERMISSION_CODES.USER_SELF_UPDATE_PROFILE,
  PERMISSION_CODES.USER_SELF_CHANGE_PASSWORD,
]

export const PAYMENT_APPROVAL_PERMISSIONS = [
  PERMISSION_CODES.PAYMENT_APPROVE_LEVEL_1,
  PERMISSION_CODES.PAYMENT_APPROVE_LEVEL_2,
  PERMISSION_CODES.PAYMENT_APPROVE_FINAL,
]

export const WAREHOUSE_INBOUND_APPROVAL_PERMISSIONS = [
  PERMISSION_CODES.WAREHOUSE_INBOUND_APPROVE_LEVEL_1,
  PERMISSION_CODES.WAREHOUSE_INBOUND_APPROVE_LEVEL_2,
  PERMISSION_CODES.WAREHOUSE_INBOUND_APPROVE_FINAL,
]

export const hasPermission = (code: string) => {
  return getPermissionsFromCookie().includes(code)
}

export const hasAnyPermission = (codes: string[]) => {
  return codes.some(hasPermission)
}
