/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as R404Import } from './routes/404'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as AppHomeImport } from './routes/_app/home'
import { Route as AppWrapperRouteImport } from './routes/_app/_wrapper/route'

// Create Virtual Routes

const AppSettingLazyImport = createFileRoute('/_app/setting')()
const AppContractLazyImport = createFileRoute('/_app/contract')()
const AppWrapperVendorIndexLazyImport = createFileRoute(
  '/_app/_wrapper/vendor/',
)()
const AppWrapperUserIndexLazyImport = createFileRoute('/_app/_wrapper/user/')()
const AppWrapperTypeIndexLazyImport = createFileRoute('/_app/_wrapper/type/')()
const AppWrapperPaymentIndexLazyImport = createFileRoute(
  '/_app/_wrapper/payment/',
)()
const AppWrapperOrderIndexLazyImport = createFileRoute(
  '/_app/_wrapper/order/',
)()
const AppWrapperInventoryStockIndexLazyImport = createFileRoute(
  '/_app/_wrapper/inventory-stock/',
)()
const AppWrapperInventoryOutIndexLazyImport = createFileRoute(
  '/_app/_wrapper/inventory-out/',
)()
const AppWrapperInventoryInIndexLazyImport = createFileRoute(
  '/_app/_wrapper/inventory-in/',
)()
const AppWrapperGoodsIndexLazyImport = createFileRoute(
  '/_app/_wrapper/goods/',
)()
const AppWrapperCustomerIndexLazyImport = createFileRoute(
  '/_app/_wrapper/customer/',
)()
const AppWrapperVendorNewLazyImport = createFileRoute(
  '/_app/_wrapper/vendor/new',
)()
const AppWrapperVendorVendorIdLazyImport = createFileRoute(
  '/_app/_wrapper/vendor/$vendorId',
)()
const AppWrapperUserNewLazyImport = createFileRoute('/_app/_wrapper/user/new')()
const AppWrapperUserAclUserIdLazyImport = createFileRoute(
  '/_app/_wrapper/user/$aclUserId',
)()
const AppWrapperTypeNewLazyImport = createFileRoute('/_app/_wrapper/type/new')()
const AppWrapperTypeTypeIdLazyImport = createFileRoute(
  '/_app/_wrapper/type/$typeId',
)()
const AppWrapperPaymentNewLazyImport = createFileRoute(
  '/_app/_wrapper/payment/new',
)()
const AppWrapperOrderNewLazyImport = createFileRoute(
  '/_app/_wrapper/order/new',
)()
const AppWrapperOrderOrderIdLazyImport = createFileRoute(
  '/_app/_wrapper/order/$orderId',
)()
const AppWrapperInventoryInInventoryCodeLazyImport = createFileRoute(
  '/_app/_wrapper/inventory-in/$inventoryCode',
)()
const AppWrapperGoodsNewLazyImport = createFileRoute(
  '/_app/_wrapper/goods/new',
)()
const AppWrapperGoodsGoodsIdLazyImport = createFileRoute(
  '/_app/_wrapper/goods/$goodsId',
)()
const AppWrapperCustomerNewLazyImport = createFileRoute(
  '/_app/_wrapper/customer/new',
)()
const AppWrapperCustomerCustomerIdLazyImport = createFileRoute(
  '/_app/_wrapper/customer/$customerId',
)()
const AppWrapperUserEditUserIdLazyImport = createFileRoute(
  '/_app/_wrapper/user/edit/$userId',
)()

// Create/Update Routes

const R404Route = R404Import.update({
  path: '/404',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppSettingLazyRoute = AppSettingLazyImport.update({
  path: '/setting',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_app/setting.lazy').then((d) => d.Route))

const AppContractLazyRoute = AppContractLazyImport.update({
  path: '/contract',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_app/contract.lazy').then((d) => d.Route))

const AuthLoginRoute = AuthLoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppHomeRoute = AppHomeImport.update({
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const AppWrapperRouteRoute = AppWrapperRouteImport.update({
  id: '/_app/_wrapper',
  getParentRoute: () => rootRoute,
} as any)

const AppWrapperVendorIndexLazyRoute = AppWrapperVendorIndexLazyImport.update({
  path: '/vendor/',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/vendor/index.lazy').then((d) => d.Route),
)

const AppWrapperUserIndexLazyRoute = AppWrapperUserIndexLazyImport.update({
  path: '/user/',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/user/index.lazy').then((d) => d.Route),
)

const AppWrapperTypeIndexLazyRoute = AppWrapperTypeIndexLazyImport.update({
  path: '/type/',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/type/index.lazy').then((d) => d.Route),
)

const AppWrapperPaymentIndexLazyRoute = AppWrapperPaymentIndexLazyImport.update(
  {
    path: '/payment/',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_app/_wrapper/payment/index.lazy').then((d) => d.Route),
)

const AppWrapperOrderIndexLazyRoute = AppWrapperOrderIndexLazyImport.update({
  path: '/order/',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/order/index.lazy').then((d) => d.Route),
)

const AppWrapperInventoryStockIndexLazyRoute =
  AppWrapperInventoryStockIndexLazyImport.update({
    path: '/inventory-stock/',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/inventory-stock/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AppWrapperInventoryOutIndexLazyRoute =
  AppWrapperInventoryOutIndexLazyImport.update({
    path: '/inventory-out/',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/inventory-out/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AppWrapperInventoryInIndexLazyRoute =
  AppWrapperInventoryInIndexLazyImport.update({
    path: '/inventory-in/',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/inventory-in/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AppWrapperGoodsIndexLazyRoute = AppWrapperGoodsIndexLazyImport.update({
  path: '/goods/',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/goods/index.lazy').then((d) => d.Route),
)

const AppWrapperCustomerIndexLazyRoute =
  AppWrapperCustomerIndexLazyImport.update({
    path: '/customer/',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/customer/index.lazy').then((d) => d.Route),
  )

const AppWrapperVendorNewLazyRoute = AppWrapperVendorNewLazyImport.update({
  path: '/vendor/new',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/vendor/new.lazy').then((d) => d.Route),
)

const AppWrapperVendorVendorIdLazyRoute =
  AppWrapperVendorVendorIdLazyImport.update({
    path: '/vendor/$vendorId',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/vendor/$vendorId.lazy').then((d) => d.Route),
  )

const AppWrapperUserNewLazyRoute = AppWrapperUserNewLazyImport.update({
  path: '/user/new',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/user/new.lazy').then((d) => d.Route),
)

const AppWrapperUserAclUserIdLazyRoute =
  AppWrapperUserAclUserIdLazyImport.update({
    path: '/user/$aclUserId',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/user/$aclUserId.lazy').then((d) => d.Route),
  )

const AppWrapperTypeNewLazyRoute = AppWrapperTypeNewLazyImport.update({
  path: '/type/new',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/type/new.lazy').then((d) => d.Route),
)

const AppWrapperTypeTypeIdLazyRoute = AppWrapperTypeTypeIdLazyImport.update({
  path: '/type/$typeId',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/type/$typeId.lazy').then((d) => d.Route),
)

const AppWrapperPaymentNewLazyRoute = AppWrapperPaymentNewLazyImport.update({
  path: '/payment/new',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/payment/new.lazy').then((d) => d.Route),
)

const AppWrapperOrderNewLazyRoute = AppWrapperOrderNewLazyImport.update({
  path: '/order/new',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/order/new.lazy').then((d) => d.Route),
)

const AppWrapperOrderOrderIdLazyRoute = AppWrapperOrderOrderIdLazyImport.update(
  {
    path: '/order/$orderId',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_app/_wrapper/order/$orderId.lazy').then((d) => d.Route),
)

const AppWrapperInventoryInInventoryCodeLazyRoute =
  AppWrapperInventoryInInventoryCodeLazyImport.update({
    path: '/inventory-in/$inventoryCode',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/inventory-in/$inventoryCode.lazy').then(
      (d) => d.Route,
    ),
  )

const AppWrapperGoodsNewLazyRoute = AppWrapperGoodsNewLazyImport.update({
  path: '/goods/new',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/goods/new.lazy').then((d) => d.Route),
)

const AppWrapperGoodsGoodsIdLazyRoute = AppWrapperGoodsGoodsIdLazyImport.update(
  {
    path: '/goods/$goodsId',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_app/_wrapper/goods/$goodsId.lazy').then((d) => d.Route),
)

const AppWrapperCustomerNewLazyRoute = AppWrapperCustomerNewLazyImport.update({
  path: '/customer/new',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/customer/new.lazy').then((d) => d.Route),
)

const AppWrapperCustomerCustomerIdLazyRoute =
  AppWrapperCustomerCustomerIdLazyImport.update({
    path: '/customer/$customerId',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/customer/$customerId.lazy').then(
      (d) => d.Route,
    ),
  )

const AppWrapperUserEditUserIdLazyRoute =
  AppWrapperUserEditUserIdLazyImport.update({
    path: '/user/edit/$userId',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/user/edit.$userId.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404Import
      parentRoute: typeof rootRoute
    }
    '/_app/_wrapper': {
      id: '/_app/_wrapper'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppWrapperRouteImport
      parentRoute: typeof rootRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/_app/contract': {
      id: '/_app/contract'
      path: '/contract'
      fullPath: '/contract'
      preLoaderRoute: typeof AppContractLazyImport
      parentRoute: typeof rootRoute
    }
    '/_app/setting': {
      id: '/_app/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof AppSettingLazyImport
      parentRoute: typeof rootRoute
    }
    '/_app/_wrapper/customer/$customerId': {
      id: '/_app/_wrapper/customer/$customerId'
      path: '/customer/$customerId'
      fullPath: '/customer/$customerId'
      preLoaderRoute: typeof AppWrapperCustomerCustomerIdLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/customer/new': {
      id: '/_app/_wrapper/customer/new'
      path: '/customer/new'
      fullPath: '/customer/new'
      preLoaderRoute: typeof AppWrapperCustomerNewLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/goods/$goodsId': {
      id: '/_app/_wrapper/goods/$goodsId'
      path: '/goods/$goodsId'
      fullPath: '/goods/$goodsId'
      preLoaderRoute: typeof AppWrapperGoodsGoodsIdLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/goods/new': {
      id: '/_app/_wrapper/goods/new'
      path: '/goods/new'
      fullPath: '/goods/new'
      preLoaderRoute: typeof AppWrapperGoodsNewLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/inventory-in/$inventoryCode': {
      id: '/_app/_wrapper/inventory-in/$inventoryCode'
      path: '/inventory-in/$inventoryCode'
      fullPath: '/inventory-in/$inventoryCode'
      preLoaderRoute: typeof AppWrapperInventoryInInventoryCodeLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/order/$orderId': {
      id: '/_app/_wrapper/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof AppWrapperOrderOrderIdLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/order/new': {
      id: '/_app/_wrapper/order/new'
      path: '/order/new'
      fullPath: '/order/new'
      preLoaderRoute: typeof AppWrapperOrderNewLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/payment/new': {
      id: '/_app/_wrapper/payment/new'
      path: '/payment/new'
      fullPath: '/payment/new'
      preLoaderRoute: typeof AppWrapperPaymentNewLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/type/$typeId': {
      id: '/_app/_wrapper/type/$typeId'
      path: '/type/$typeId'
      fullPath: '/type/$typeId'
      preLoaderRoute: typeof AppWrapperTypeTypeIdLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/type/new': {
      id: '/_app/_wrapper/type/new'
      path: '/type/new'
      fullPath: '/type/new'
      preLoaderRoute: typeof AppWrapperTypeNewLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/user/$aclUserId': {
      id: '/_app/_wrapper/user/$aclUserId'
      path: '/user/$aclUserId'
      fullPath: '/user/$aclUserId'
      preLoaderRoute: typeof AppWrapperUserAclUserIdLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/user/new': {
      id: '/_app/_wrapper/user/new'
      path: '/user/new'
      fullPath: '/user/new'
      preLoaderRoute: typeof AppWrapperUserNewLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/vendor/$vendorId': {
      id: '/_app/_wrapper/vendor/$vendorId'
      path: '/vendor/$vendorId'
      fullPath: '/vendor/$vendorId'
      preLoaderRoute: typeof AppWrapperVendorVendorIdLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/vendor/new': {
      id: '/_app/_wrapper/vendor/new'
      path: '/vendor/new'
      fullPath: '/vendor/new'
      preLoaderRoute: typeof AppWrapperVendorNewLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/customer/': {
      id: '/_app/_wrapper/customer/'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof AppWrapperCustomerIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/goods/': {
      id: '/_app/_wrapper/goods/'
      path: '/goods'
      fullPath: '/goods'
      preLoaderRoute: typeof AppWrapperGoodsIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/inventory-in/': {
      id: '/_app/_wrapper/inventory-in/'
      path: '/inventory-in'
      fullPath: '/inventory-in'
      preLoaderRoute: typeof AppWrapperInventoryInIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/inventory-out/': {
      id: '/_app/_wrapper/inventory-out/'
      path: '/inventory-out'
      fullPath: '/inventory-out'
      preLoaderRoute: typeof AppWrapperInventoryOutIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/inventory-stock/': {
      id: '/_app/_wrapper/inventory-stock/'
      path: '/inventory-stock'
      fullPath: '/inventory-stock'
      preLoaderRoute: typeof AppWrapperInventoryStockIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/order/': {
      id: '/_app/_wrapper/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof AppWrapperOrderIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/payment/': {
      id: '/_app/_wrapper/payment/'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof AppWrapperPaymentIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/type/': {
      id: '/_app/_wrapper/type/'
      path: '/type'
      fullPath: '/type'
      preLoaderRoute: typeof AppWrapperTypeIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/user/': {
      id: '/_app/_wrapper/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AppWrapperUserIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/vendor/': {
      id: '/_app/_wrapper/vendor/'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AppWrapperVendorIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/user/edit/$userId': {
      id: '/_app/_wrapper/user/edit/$userId'
      path: '/user/edit/$userId'
      fullPath: '/user/edit/$userId'
      preLoaderRoute: typeof AppWrapperUserEditUserIdLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
  }
}

// Create and export the route tree

interface AppWrapperRouteRouteChildren {
  AppWrapperCustomerCustomerIdLazyRoute: typeof AppWrapperCustomerCustomerIdLazyRoute
  AppWrapperCustomerNewLazyRoute: typeof AppWrapperCustomerNewLazyRoute
  AppWrapperGoodsGoodsIdLazyRoute: typeof AppWrapperGoodsGoodsIdLazyRoute
  AppWrapperGoodsNewLazyRoute: typeof AppWrapperGoodsNewLazyRoute
  AppWrapperInventoryInInventoryCodeLazyRoute: typeof AppWrapperInventoryInInventoryCodeLazyRoute
  AppWrapperOrderOrderIdLazyRoute: typeof AppWrapperOrderOrderIdLazyRoute
  AppWrapperOrderNewLazyRoute: typeof AppWrapperOrderNewLazyRoute
  AppWrapperPaymentNewLazyRoute: typeof AppWrapperPaymentNewLazyRoute
  AppWrapperTypeTypeIdLazyRoute: typeof AppWrapperTypeTypeIdLazyRoute
  AppWrapperTypeNewLazyRoute: typeof AppWrapperTypeNewLazyRoute
  AppWrapperUserAclUserIdLazyRoute: typeof AppWrapperUserAclUserIdLazyRoute
  AppWrapperUserNewLazyRoute: typeof AppWrapperUserNewLazyRoute
  AppWrapperVendorVendorIdLazyRoute: typeof AppWrapperVendorVendorIdLazyRoute
  AppWrapperVendorNewLazyRoute: typeof AppWrapperVendorNewLazyRoute
  AppWrapperCustomerIndexLazyRoute: typeof AppWrapperCustomerIndexLazyRoute
  AppWrapperGoodsIndexLazyRoute: typeof AppWrapperGoodsIndexLazyRoute
  AppWrapperInventoryInIndexLazyRoute: typeof AppWrapperInventoryInIndexLazyRoute
  AppWrapperInventoryOutIndexLazyRoute: typeof AppWrapperInventoryOutIndexLazyRoute
  AppWrapperInventoryStockIndexLazyRoute: typeof AppWrapperInventoryStockIndexLazyRoute
  AppWrapperOrderIndexLazyRoute: typeof AppWrapperOrderIndexLazyRoute
  AppWrapperPaymentIndexLazyRoute: typeof AppWrapperPaymentIndexLazyRoute
  AppWrapperTypeIndexLazyRoute: typeof AppWrapperTypeIndexLazyRoute
  AppWrapperUserIndexLazyRoute: typeof AppWrapperUserIndexLazyRoute
  AppWrapperVendorIndexLazyRoute: typeof AppWrapperVendorIndexLazyRoute
  AppWrapperUserEditUserIdLazyRoute: typeof AppWrapperUserEditUserIdLazyRoute
}

const AppWrapperRouteRouteChildren: AppWrapperRouteRouteChildren = {
  AppWrapperCustomerCustomerIdLazyRoute: AppWrapperCustomerCustomerIdLazyRoute,
  AppWrapperCustomerNewLazyRoute: AppWrapperCustomerNewLazyRoute,
  AppWrapperGoodsGoodsIdLazyRoute: AppWrapperGoodsGoodsIdLazyRoute,
  AppWrapperGoodsNewLazyRoute: AppWrapperGoodsNewLazyRoute,
  AppWrapperInventoryInInventoryCodeLazyRoute:
    AppWrapperInventoryInInventoryCodeLazyRoute,
  AppWrapperOrderOrderIdLazyRoute: AppWrapperOrderOrderIdLazyRoute,
  AppWrapperOrderNewLazyRoute: AppWrapperOrderNewLazyRoute,
  AppWrapperPaymentNewLazyRoute: AppWrapperPaymentNewLazyRoute,
  AppWrapperTypeTypeIdLazyRoute: AppWrapperTypeTypeIdLazyRoute,
  AppWrapperTypeNewLazyRoute: AppWrapperTypeNewLazyRoute,
  AppWrapperUserAclUserIdLazyRoute: AppWrapperUserAclUserIdLazyRoute,
  AppWrapperUserNewLazyRoute: AppWrapperUserNewLazyRoute,
  AppWrapperVendorVendorIdLazyRoute: AppWrapperVendorVendorIdLazyRoute,
  AppWrapperVendorNewLazyRoute: AppWrapperVendorNewLazyRoute,
  AppWrapperCustomerIndexLazyRoute: AppWrapperCustomerIndexLazyRoute,
  AppWrapperGoodsIndexLazyRoute: AppWrapperGoodsIndexLazyRoute,
  AppWrapperInventoryInIndexLazyRoute: AppWrapperInventoryInIndexLazyRoute,
  AppWrapperInventoryOutIndexLazyRoute: AppWrapperInventoryOutIndexLazyRoute,
  AppWrapperInventoryStockIndexLazyRoute:
    AppWrapperInventoryStockIndexLazyRoute,
  AppWrapperOrderIndexLazyRoute: AppWrapperOrderIndexLazyRoute,
  AppWrapperPaymentIndexLazyRoute: AppWrapperPaymentIndexLazyRoute,
  AppWrapperTypeIndexLazyRoute: AppWrapperTypeIndexLazyRoute,
  AppWrapperUserIndexLazyRoute: AppWrapperUserIndexLazyRoute,
  AppWrapperVendorIndexLazyRoute: AppWrapperVendorIndexLazyRoute,
  AppWrapperUserEditUserIdLazyRoute: AppWrapperUserEditUserIdLazyRoute,
}

const AppWrapperRouteRouteWithChildren = AppWrapperRouteRoute._addFileChildren(
  AppWrapperRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '': typeof AppWrapperRouteRouteWithChildren
  '/home': typeof AppHomeRoute
  '/login': typeof AuthLoginRoute
  '/contract': typeof AppContractLazyRoute
  '/setting': typeof AppSettingLazyRoute
  '/customer/$customerId': typeof AppWrapperCustomerCustomerIdLazyRoute
  '/customer/new': typeof AppWrapperCustomerNewLazyRoute
  '/goods/$goodsId': typeof AppWrapperGoodsGoodsIdLazyRoute
  '/goods/new': typeof AppWrapperGoodsNewLazyRoute
  '/inventory-in/$inventoryCode': typeof AppWrapperInventoryInInventoryCodeLazyRoute
  '/order/$orderId': typeof AppWrapperOrderOrderIdLazyRoute
  '/order/new': typeof AppWrapperOrderNewLazyRoute
  '/payment/new': typeof AppWrapperPaymentNewLazyRoute
  '/type/$typeId': typeof AppWrapperTypeTypeIdLazyRoute
  '/type/new': typeof AppWrapperTypeNewLazyRoute
  '/user/$aclUserId': typeof AppWrapperUserAclUserIdLazyRoute
  '/user/new': typeof AppWrapperUserNewLazyRoute
  '/vendor/$vendorId': typeof AppWrapperVendorVendorIdLazyRoute
  '/vendor/new': typeof AppWrapperVendorNewLazyRoute
  '/customer': typeof AppWrapperCustomerIndexLazyRoute
  '/goods': typeof AppWrapperGoodsIndexLazyRoute
  '/inventory-in': typeof AppWrapperInventoryInIndexLazyRoute
  '/inventory-out': typeof AppWrapperInventoryOutIndexLazyRoute
  '/inventory-stock': typeof AppWrapperInventoryStockIndexLazyRoute
  '/order': typeof AppWrapperOrderIndexLazyRoute
  '/payment': typeof AppWrapperPaymentIndexLazyRoute
  '/type': typeof AppWrapperTypeIndexLazyRoute
  '/user': typeof AppWrapperUserIndexLazyRoute
  '/vendor': typeof AppWrapperVendorIndexLazyRoute
  '/user/edit/$userId': typeof AppWrapperUserEditUserIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '': typeof AppWrapperRouteRouteWithChildren
  '/home': typeof AppHomeRoute
  '/login': typeof AuthLoginRoute
  '/contract': typeof AppContractLazyRoute
  '/setting': typeof AppSettingLazyRoute
  '/customer/$customerId': typeof AppWrapperCustomerCustomerIdLazyRoute
  '/customer/new': typeof AppWrapperCustomerNewLazyRoute
  '/goods/$goodsId': typeof AppWrapperGoodsGoodsIdLazyRoute
  '/goods/new': typeof AppWrapperGoodsNewLazyRoute
  '/inventory-in/$inventoryCode': typeof AppWrapperInventoryInInventoryCodeLazyRoute
  '/order/$orderId': typeof AppWrapperOrderOrderIdLazyRoute
  '/order/new': typeof AppWrapperOrderNewLazyRoute
  '/payment/new': typeof AppWrapperPaymentNewLazyRoute
  '/type/$typeId': typeof AppWrapperTypeTypeIdLazyRoute
  '/type/new': typeof AppWrapperTypeNewLazyRoute
  '/user/$aclUserId': typeof AppWrapperUserAclUserIdLazyRoute
  '/user/new': typeof AppWrapperUserNewLazyRoute
  '/vendor/$vendorId': typeof AppWrapperVendorVendorIdLazyRoute
  '/vendor/new': typeof AppWrapperVendorNewLazyRoute
  '/customer': typeof AppWrapperCustomerIndexLazyRoute
  '/goods': typeof AppWrapperGoodsIndexLazyRoute
  '/inventory-in': typeof AppWrapperInventoryInIndexLazyRoute
  '/inventory-out': typeof AppWrapperInventoryOutIndexLazyRoute
  '/inventory-stock': typeof AppWrapperInventoryStockIndexLazyRoute
  '/order': typeof AppWrapperOrderIndexLazyRoute
  '/payment': typeof AppWrapperPaymentIndexLazyRoute
  '/type': typeof AppWrapperTypeIndexLazyRoute
  '/user': typeof AppWrapperUserIndexLazyRoute
  '/vendor': typeof AppWrapperVendorIndexLazyRoute
  '/user/edit/$userId': typeof AppWrapperUserEditUserIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_app/_wrapper': typeof AppWrapperRouteRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/contract': typeof AppContractLazyRoute
  '/_app/setting': typeof AppSettingLazyRoute
  '/_app/_wrapper/customer/$customerId': typeof AppWrapperCustomerCustomerIdLazyRoute
  '/_app/_wrapper/customer/new': typeof AppWrapperCustomerNewLazyRoute
  '/_app/_wrapper/goods/$goodsId': typeof AppWrapperGoodsGoodsIdLazyRoute
  '/_app/_wrapper/goods/new': typeof AppWrapperGoodsNewLazyRoute
  '/_app/_wrapper/inventory-in/$inventoryCode': typeof AppWrapperInventoryInInventoryCodeLazyRoute
  '/_app/_wrapper/order/$orderId': typeof AppWrapperOrderOrderIdLazyRoute
  '/_app/_wrapper/order/new': typeof AppWrapperOrderNewLazyRoute
  '/_app/_wrapper/payment/new': typeof AppWrapperPaymentNewLazyRoute
  '/_app/_wrapper/type/$typeId': typeof AppWrapperTypeTypeIdLazyRoute
  '/_app/_wrapper/type/new': typeof AppWrapperTypeNewLazyRoute
  '/_app/_wrapper/user/$aclUserId': typeof AppWrapperUserAclUserIdLazyRoute
  '/_app/_wrapper/user/new': typeof AppWrapperUserNewLazyRoute
  '/_app/_wrapper/vendor/$vendorId': typeof AppWrapperVendorVendorIdLazyRoute
  '/_app/_wrapper/vendor/new': typeof AppWrapperVendorNewLazyRoute
  '/_app/_wrapper/customer/': typeof AppWrapperCustomerIndexLazyRoute
  '/_app/_wrapper/goods/': typeof AppWrapperGoodsIndexLazyRoute
  '/_app/_wrapper/inventory-in/': typeof AppWrapperInventoryInIndexLazyRoute
  '/_app/_wrapper/inventory-out/': typeof AppWrapperInventoryOutIndexLazyRoute
  '/_app/_wrapper/inventory-stock/': typeof AppWrapperInventoryStockIndexLazyRoute
  '/_app/_wrapper/order/': typeof AppWrapperOrderIndexLazyRoute
  '/_app/_wrapper/payment/': typeof AppWrapperPaymentIndexLazyRoute
  '/_app/_wrapper/type/': typeof AppWrapperTypeIndexLazyRoute
  '/_app/_wrapper/user/': typeof AppWrapperUserIndexLazyRoute
  '/_app/_wrapper/vendor/': typeof AppWrapperVendorIndexLazyRoute
  '/_app/_wrapper/user/edit/$userId': typeof AppWrapperUserEditUserIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | ''
    | '/home'
    | '/login'
    | '/contract'
    | '/setting'
    | '/customer/$customerId'
    | '/customer/new'
    | '/goods/$goodsId'
    | '/goods/new'
    | '/inventory-in/$inventoryCode'
    | '/order/$orderId'
    | '/order/new'
    | '/payment/new'
    | '/type/$typeId'
    | '/type/new'
    | '/user/$aclUserId'
    | '/user/new'
    | '/vendor/$vendorId'
    | '/vendor/new'
    | '/customer'
    | '/goods'
    | '/inventory-in'
    | '/inventory-out'
    | '/inventory-stock'
    | '/order'
    | '/payment'
    | '/type'
    | '/user'
    | '/vendor'
    | '/user/edit/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | ''
    | '/home'
    | '/login'
    | '/contract'
    | '/setting'
    | '/customer/$customerId'
    | '/customer/new'
    | '/goods/$goodsId'
    | '/goods/new'
    | '/inventory-in/$inventoryCode'
    | '/order/$orderId'
    | '/order/new'
    | '/payment/new'
    | '/type/$typeId'
    | '/type/new'
    | '/user/$aclUserId'
    | '/user/new'
    | '/vendor/$vendorId'
    | '/vendor/new'
    | '/customer'
    | '/goods'
    | '/inventory-in'
    | '/inventory-out'
    | '/inventory-stock'
    | '/order'
    | '/payment'
    | '/type'
    | '/user'
    | '/vendor'
    | '/user/edit/$userId'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/_app/_wrapper'
    | '/_app/home'
    | '/_auth/login'
    | '/_app/contract'
    | '/_app/setting'
    | '/_app/_wrapper/customer/$customerId'
    | '/_app/_wrapper/customer/new'
    | '/_app/_wrapper/goods/$goodsId'
    | '/_app/_wrapper/goods/new'
    | '/_app/_wrapper/inventory-in/$inventoryCode'
    | '/_app/_wrapper/order/$orderId'
    | '/_app/_wrapper/order/new'
    | '/_app/_wrapper/payment/new'
    | '/_app/_wrapper/type/$typeId'
    | '/_app/_wrapper/type/new'
    | '/_app/_wrapper/user/$aclUserId'
    | '/_app/_wrapper/user/new'
    | '/_app/_wrapper/vendor/$vendorId'
    | '/_app/_wrapper/vendor/new'
    | '/_app/_wrapper/customer/'
    | '/_app/_wrapper/goods/'
    | '/_app/_wrapper/inventory-in/'
    | '/_app/_wrapper/inventory-out/'
    | '/_app/_wrapper/inventory-stock/'
    | '/_app/_wrapper/order/'
    | '/_app/_wrapper/payment/'
    | '/_app/_wrapper/type/'
    | '/_app/_wrapper/user/'
    | '/_app/_wrapper/vendor/'
    | '/_app/_wrapper/user/edit/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AppWrapperRouteRoute: typeof AppWrapperRouteRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AppContractLazyRoute: typeof AppContractLazyRoute
  AppSettingLazyRoute: typeof AppSettingLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AppWrapperRouteRoute: AppWrapperRouteRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AuthLoginRoute: AuthLoginRoute,
  AppContractLazyRoute: AppContractLazyRoute,
  AppSettingLazyRoute: AppSettingLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/404",
        "/_app/_wrapper",
        "/_app/home",
        "/_auth/login",
        "/_app/contract",
        "/_app/setting"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/404": {
      "filePath": "404.tsx"
    },
    "/_app/_wrapper": {
      "filePath": "_app/_wrapper/route.tsx",
      "children": [
        "/_app/_wrapper/customer/$customerId",
        "/_app/_wrapper/customer/new",
        "/_app/_wrapper/goods/$goodsId",
        "/_app/_wrapper/goods/new",
        "/_app/_wrapper/inventory-in/$inventoryCode",
        "/_app/_wrapper/order/$orderId",
        "/_app/_wrapper/order/new",
        "/_app/_wrapper/payment/new",
        "/_app/_wrapper/type/$typeId",
        "/_app/_wrapper/type/new",
        "/_app/_wrapper/user/$aclUserId",
        "/_app/_wrapper/user/new",
        "/_app/_wrapper/vendor/$vendorId",
        "/_app/_wrapper/vendor/new",
        "/_app/_wrapper/customer/",
        "/_app/_wrapper/goods/",
        "/_app/_wrapper/inventory-in/",
        "/_app/_wrapper/inventory-out/",
        "/_app/_wrapper/inventory-stock/",
        "/_app/_wrapper/order/",
        "/_app/_wrapper/payment/",
        "/_app/_wrapper/type/",
        "/_app/_wrapper/user/",
        "/_app/_wrapper/vendor/",
        "/_app/_wrapper/user/edit/$userId"
      ]
    },
    "/_app/home": {
      "filePath": "_app/home.tsx"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx"
    },
    "/_app/contract": {
      "filePath": "_app/contract.lazy.tsx"
    },
    "/_app/setting": {
      "filePath": "_app/setting.lazy.tsx"
    },
    "/_app/_wrapper/customer/$customerId": {
      "filePath": "_app/_wrapper/customer/$customerId.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/customer/new": {
      "filePath": "_app/_wrapper/customer/new.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/goods/$goodsId": {
      "filePath": "_app/_wrapper/goods/$goodsId.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/goods/new": {
      "filePath": "_app/_wrapper/goods/new.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/inventory-in/$inventoryCode": {
      "filePath": "_app/_wrapper/inventory-in/$inventoryCode.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/order/$orderId": {
      "filePath": "_app/_wrapper/order/$orderId.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/order/new": {
      "filePath": "_app/_wrapper/order/new.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/payment/new": {
      "filePath": "_app/_wrapper/payment/new.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/type/$typeId": {
      "filePath": "_app/_wrapper/type/$typeId.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/type/new": {
      "filePath": "_app/_wrapper/type/new.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/user/$aclUserId": {
      "filePath": "_app/_wrapper/user/$aclUserId.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/user/new": {
      "filePath": "_app/_wrapper/user/new.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/vendor/$vendorId": {
      "filePath": "_app/_wrapper/vendor/$vendorId.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/vendor/new": {
      "filePath": "_app/_wrapper/vendor/new.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/customer/": {
      "filePath": "_app/_wrapper/customer/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/goods/": {
      "filePath": "_app/_wrapper/goods/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/inventory-in/": {
      "filePath": "_app/_wrapper/inventory-in/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/inventory-out/": {
      "filePath": "_app/_wrapper/inventory-out/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/inventory-stock/": {
      "filePath": "_app/_wrapper/inventory-stock/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/order/": {
      "filePath": "_app/_wrapper/order/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/payment/": {
      "filePath": "_app/_wrapper/payment/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/type/": {
      "filePath": "_app/_wrapper/type/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/user/": {
      "filePath": "_app/_wrapper/user/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/vendor/": {
      "filePath": "_app/_wrapper/vendor/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/user/edit/$userId": {
      "filePath": "_app/_wrapper/user/edit.$userId.lazy.tsx",
      "parent": "/_app/_wrapper"
    }
  }
}
ROUTE_MANIFEST_END */
