/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as R404Import } from './routes/404'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as AppHomeImport } from './routes/_app/home'
import { Route as AppWrapperRouteImport } from './routes/_app/_wrapper/route'
import { Route as AppWrapperUserRouteImport } from './routes/_app/_wrapper/user/route'

// Create Virtual Routes

const AppSettingLazyImport = createFileRoute('/_app/setting')()
const AppContractLazyImport = createFileRoute('/_app/contract')()
const AppWrapperWarehouseInboundIndexLazyImport = createFileRoute(
  '/_app/_wrapper/warehouse-inbound/',
)()
const AppWrapperVendorIndexLazyImport = createFileRoute(
  '/_app/_wrapper/vendor/',
)()
const AppWrapperUserIndexLazyImport = createFileRoute('/_app/_wrapper/user/')()
const AppWrapperTypeIndexLazyImport = createFileRoute('/_app/_wrapper/type/')()
const AppWrapperPurchaseIndexLazyImport = createFileRoute(
  '/_app/_wrapper/purchase/',
)()
const AppWrapperPaymentIndexLazyImport = createFileRoute(
  '/_app/_wrapper/payment/',
)()
const AppWrapperOrderIndexLazyImport = createFileRoute(
  '/_app/_wrapper/order/',
)()
const AppWrapperNotificationsIndexLazyImport = createFileRoute(
  '/_app/_wrapper/notifications/',
)()
const AppWrapperInventoryStockIndexLazyImport = createFileRoute(
  '/_app/_wrapper/inventory-stock/',
)()
const AppWrapperInventoryOutIndexLazyImport = createFileRoute(
  '/_app/_wrapper/inventory-out/',
)()
const AppWrapperInventoryInIndexLazyImport = createFileRoute(
  '/_app/_wrapper/inventory-in/',
)()
const AppWrapperGoodsIndexLazyImport = createFileRoute(
  '/_app/_wrapper/goods/',
)()
const AppWrapperCustomerIndexLazyImport = createFileRoute(
  '/_app/_wrapper/customer/',
)()
const AppWrapperWarehouseInboundPaymentRequestIdLazyImport = createFileRoute(
  '/_app/_wrapper/warehouse-inbound/$paymentRequestId',
)()
const AppWrapperVendorNewLazyImport = createFileRoute(
  '/_app/_wrapper/vendor/new',
)()
const AppWrapperVendorVendorIdLazyImport = createFileRoute(
  '/_app/_wrapper/vendor/$vendorId',
)()
const AppWrapperUserNewLazyImport = createFileRoute('/_app/_wrapper/user/new')()
const AppWrapperUserAclUserIdLazyImport = createFileRoute(
  '/_app/_wrapper/user/$aclUserId',
)()
const AppWrapperTypeNewLazyImport = createFileRoute('/_app/_wrapper/type/new')()
const AppWrapperTypeTypeIdLazyImport = createFileRoute(
  '/_app/_wrapper/type/$typeId',
)()
const AppWrapperPurchaseNewLazyImport = createFileRoute(
  '/_app/_wrapper/purchase/new',
)()
const AppWrapperPurchasePurchaseIdLazyImport = createFileRoute(
  '/_app/_wrapper/purchase/$purchaseId',
)()
const AppWrapperPaymentNewLazyImport = createFileRoute(
  '/_app/_wrapper/payment/new',
)()
const AppWrapperPaymentPaymentIdLazyImport = createFileRoute(
  '/_app/_wrapper/payment/$paymentId',
)()
const AppWrapperOrderNewLazyImport = createFileRoute(
  '/_app/_wrapper/order/new',
)()
const AppWrapperOrderOrderIdLazyImport = createFileRoute(
  '/_app/_wrapper/order/$orderId',
)()
const AppWrapperInventoryInInventoryCodeLazyImport = createFileRoute(
  '/_app/_wrapper/inventory-in/$inventoryCode',
)()
const AppWrapperGoodsNewLazyImport = createFileRoute(
  '/_app/_wrapper/goods/new',
)()
const AppWrapperGoodsGoodsIdLazyImport = createFileRoute(
  '/_app/_wrapper/goods/$goodsId',
)()
const AppWrapperCustomerNewLazyImport = createFileRoute(
  '/_app/_wrapper/customer/new',
)()
const AppWrapperCustomerCustomerIdLazyImport = createFileRoute(
  '/_app/_wrapper/customer/$customerId',
)()
const AppWrapperWarehouseInboundReceiptReceiptIdLazyImport = createFileRoute(
  '/_app/_wrapper/warehouse-inbound/receipt/$receiptId',
)()
const AppWrapperUserEditUserIdLazyImport = createFileRoute(
  '/_app/_wrapper/user/edit/$userId',
)()

// Create/Update Routes

const R404Route = R404Import.update({
  path: '/404',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppSettingLazyRoute = AppSettingLazyImport.update({
  path: '/setting',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_app/setting.lazy').then((d) => d.Route))

const AppContractLazyRoute = AppContractLazyImport.update({
  path: '/contract',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_app/contract.lazy').then((d) => d.Route))

const AuthLoginRoute = AuthLoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppHomeRoute = AppHomeImport.update({
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const AppWrapperRouteRoute = AppWrapperRouteImport.update({
  id: '/_app/_wrapper',
  getParentRoute: () => rootRoute,
} as any)

const AppWrapperUserRouteRoute = AppWrapperUserRouteImport.update({
  path: '/user',
  getParentRoute: () => AppWrapperRouteRoute,
} as any)

const AppWrapperWarehouseInboundIndexLazyRoute =
  AppWrapperWarehouseInboundIndexLazyImport.update({
    path: '/warehouse-inbound/',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/warehouse-inbound/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AppWrapperVendorIndexLazyRoute = AppWrapperVendorIndexLazyImport.update({
  path: '/vendor/',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/vendor/index.lazy').then((d) => d.Route),
)

const AppWrapperUserIndexLazyRoute = AppWrapperUserIndexLazyImport.update({
  path: '/',
  getParentRoute: () => AppWrapperUserRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/user/index.lazy').then((d) => d.Route),
)

const AppWrapperTypeIndexLazyRoute = AppWrapperTypeIndexLazyImport.update({
  path: '/type/',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/type/index.lazy').then((d) => d.Route),
)

const AppWrapperPurchaseIndexLazyRoute =
  AppWrapperPurchaseIndexLazyImport.update({
    path: '/purchase/',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/purchase/index.lazy').then((d) => d.Route),
  )

const AppWrapperPaymentIndexLazyRoute = AppWrapperPaymentIndexLazyImport.update(
  {
    path: '/payment/',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_app/_wrapper/payment/index.lazy').then((d) => d.Route),
)

const AppWrapperOrderIndexLazyRoute = AppWrapperOrderIndexLazyImport.update({
  path: '/order/',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/order/index.lazy').then((d) => d.Route),
)

const AppWrapperNotificationsIndexLazyRoute =
  AppWrapperNotificationsIndexLazyImport.update({
    path: '/notifications/',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/notifications/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AppWrapperInventoryStockIndexLazyRoute =
  AppWrapperInventoryStockIndexLazyImport.update({
    path: '/inventory-stock/',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/inventory-stock/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AppWrapperInventoryOutIndexLazyRoute =
  AppWrapperInventoryOutIndexLazyImport.update({
    path: '/inventory-out/',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/inventory-out/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AppWrapperInventoryInIndexLazyRoute =
  AppWrapperInventoryInIndexLazyImport.update({
    path: '/inventory-in/',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/inventory-in/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AppWrapperGoodsIndexLazyRoute = AppWrapperGoodsIndexLazyImport.update({
  path: '/goods/',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/goods/index.lazy').then((d) => d.Route),
)

const AppWrapperCustomerIndexLazyRoute =
  AppWrapperCustomerIndexLazyImport.update({
    path: '/customer/',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/customer/index.lazy').then((d) => d.Route),
  )

const AppWrapperWarehouseInboundPaymentRequestIdLazyRoute =
  AppWrapperWarehouseInboundPaymentRequestIdLazyImport.update({
    path: '/warehouse-inbound/$paymentRequestId',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_app/_wrapper/warehouse-inbound/$paymentRequestId.lazy'
    ).then((d) => d.Route),
  )

const AppWrapperVendorNewLazyRoute = AppWrapperVendorNewLazyImport.update({
  path: '/vendor/new',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/vendor/new.lazy').then((d) => d.Route),
)

const AppWrapperVendorVendorIdLazyRoute =
  AppWrapperVendorVendorIdLazyImport.update({
    path: '/vendor/$vendorId',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/vendor/$vendorId.lazy').then((d) => d.Route),
  )

const AppWrapperUserNewLazyRoute = AppWrapperUserNewLazyImport.update({
  path: '/new',
  getParentRoute: () => AppWrapperUserRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/user/new.lazy').then((d) => d.Route),
)

const AppWrapperUserAclUserIdLazyRoute =
  AppWrapperUserAclUserIdLazyImport.update({
    path: '/$aclUserId',
    getParentRoute: () => AppWrapperUserRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/user/$aclUserId.lazy').then((d) => d.Route),
  )

const AppWrapperTypeNewLazyRoute = AppWrapperTypeNewLazyImport.update({
  path: '/type/new',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/type/new.lazy').then((d) => d.Route),
)

const AppWrapperTypeTypeIdLazyRoute = AppWrapperTypeTypeIdLazyImport.update({
  path: '/type/$typeId',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/type/$typeId.lazy').then((d) => d.Route),
)

const AppWrapperPurchaseNewLazyRoute = AppWrapperPurchaseNewLazyImport.update({
  path: '/purchase/new',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/purchase/new.lazy').then((d) => d.Route),
)

const AppWrapperPurchasePurchaseIdLazyRoute =
  AppWrapperPurchasePurchaseIdLazyImport.update({
    path: '/purchase/$purchaseId',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/purchase/$purchaseId.lazy').then(
      (d) => d.Route,
    ),
  )

const AppWrapperPaymentNewLazyRoute = AppWrapperPaymentNewLazyImport.update({
  path: '/payment/new',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/payment/new.lazy').then((d) => d.Route),
)

const AppWrapperPaymentPaymentIdLazyRoute =
  AppWrapperPaymentPaymentIdLazyImport.update({
    path: '/payment/$paymentId',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/payment/$paymentId.lazy').then(
      (d) => d.Route,
    ),
  )

const AppWrapperOrderNewLazyRoute = AppWrapperOrderNewLazyImport.update({
  path: '/order/new',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/order/new.lazy').then((d) => d.Route),
)

const AppWrapperOrderOrderIdLazyRoute = AppWrapperOrderOrderIdLazyImport.update(
  {
    path: '/order/$orderId',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_app/_wrapper/order/$orderId.lazy').then((d) => d.Route),
)

const AppWrapperInventoryInInventoryCodeLazyRoute =
  AppWrapperInventoryInInventoryCodeLazyImport.update({
    path: '/inventory-in/$inventoryCode',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/inventory-in/$inventoryCode.lazy').then(
      (d) => d.Route,
    ),
  )

const AppWrapperGoodsNewLazyRoute = AppWrapperGoodsNewLazyImport.update({
  path: '/goods/new',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/goods/new.lazy').then((d) => d.Route),
)

const AppWrapperGoodsGoodsIdLazyRoute = AppWrapperGoodsGoodsIdLazyImport.update(
  {
    path: '/goods/$goodsId',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_app/_wrapper/goods/$goodsId.lazy').then((d) => d.Route),
)

const AppWrapperCustomerNewLazyRoute = AppWrapperCustomerNewLazyImport.update({
  path: '/customer/new',
  getParentRoute: () => AppWrapperRouteRoute,
} as any).lazy(() =>
  import('./routes/_app/_wrapper/customer/new.lazy').then((d) => d.Route),
)

const AppWrapperCustomerCustomerIdLazyRoute =
  AppWrapperCustomerCustomerIdLazyImport.update({
    path: '/customer/$customerId',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/customer/$customerId.lazy').then(
      (d) => d.Route,
    ),
  )

const AppWrapperWarehouseInboundReceiptReceiptIdLazyRoute =
  AppWrapperWarehouseInboundReceiptReceiptIdLazyImport.update({
    path: '/warehouse-inbound/receipt/$receiptId',
    getParentRoute: () => AppWrapperRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_app/_wrapper/warehouse-inbound/receipt.$receiptId.lazy'
    ).then((d) => d.Route),
  )

const AppWrapperUserEditUserIdLazyRoute =
  AppWrapperUserEditUserIdLazyImport.update({
    path: '/edit/$userId',
    getParentRoute: () => AppWrapperUserRouteRoute,
  } as any).lazy(() =>
    import('./routes/_app/_wrapper/user/edit.$userId.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404Import
      parentRoute: typeof rootRoute
    }
    '/_app/_wrapper': {
      id: '/_app/_wrapper'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppWrapperRouteImport
      parentRoute: typeof rootRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/_app/contract': {
      id: '/_app/contract'
      path: '/contract'
      fullPath: '/contract'
      preLoaderRoute: typeof AppContractLazyImport
      parentRoute: typeof rootRoute
    }
    '/_app/setting': {
      id: '/_app/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof AppSettingLazyImport
      parentRoute: typeof rootRoute
    }
    '/_app/_wrapper/user': {
      id: '/_app/_wrapper/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AppWrapperUserRouteImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/customer/$customerId': {
      id: '/_app/_wrapper/customer/$customerId'
      path: '/customer/$customerId'
      fullPath: '/customer/$customerId'
      preLoaderRoute: typeof AppWrapperCustomerCustomerIdLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/customer/new': {
      id: '/_app/_wrapper/customer/new'
      path: '/customer/new'
      fullPath: '/customer/new'
      preLoaderRoute: typeof AppWrapperCustomerNewLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/goods/$goodsId': {
      id: '/_app/_wrapper/goods/$goodsId'
      path: '/goods/$goodsId'
      fullPath: '/goods/$goodsId'
      preLoaderRoute: typeof AppWrapperGoodsGoodsIdLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/goods/new': {
      id: '/_app/_wrapper/goods/new'
      path: '/goods/new'
      fullPath: '/goods/new'
      preLoaderRoute: typeof AppWrapperGoodsNewLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/inventory-in/$inventoryCode': {
      id: '/_app/_wrapper/inventory-in/$inventoryCode'
      path: '/inventory-in/$inventoryCode'
      fullPath: '/inventory-in/$inventoryCode'
      preLoaderRoute: typeof AppWrapperInventoryInInventoryCodeLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/order/$orderId': {
      id: '/_app/_wrapper/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof AppWrapperOrderOrderIdLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/order/new': {
      id: '/_app/_wrapper/order/new'
      path: '/order/new'
      fullPath: '/order/new'
      preLoaderRoute: typeof AppWrapperOrderNewLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/payment/$paymentId': {
      id: '/_app/_wrapper/payment/$paymentId'
      path: '/payment/$paymentId'
      fullPath: '/payment/$paymentId'
      preLoaderRoute: typeof AppWrapperPaymentPaymentIdLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/payment/new': {
      id: '/_app/_wrapper/payment/new'
      path: '/payment/new'
      fullPath: '/payment/new'
      preLoaderRoute: typeof AppWrapperPaymentNewLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/purchase/$purchaseId': {
      id: '/_app/_wrapper/purchase/$purchaseId'
      path: '/purchase/$purchaseId'
      fullPath: '/purchase/$purchaseId'
      preLoaderRoute: typeof AppWrapperPurchasePurchaseIdLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/purchase/new': {
      id: '/_app/_wrapper/purchase/new'
      path: '/purchase/new'
      fullPath: '/purchase/new'
      preLoaderRoute: typeof AppWrapperPurchaseNewLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/type/$typeId': {
      id: '/_app/_wrapper/type/$typeId'
      path: '/type/$typeId'
      fullPath: '/type/$typeId'
      preLoaderRoute: typeof AppWrapperTypeTypeIdLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/type/new': {
      id: '/_app/_wrapper/type/new'
      path: '/type/new'
      fullPath: '/type/new'
      preLoaderRoute: typeof AppWrapperTypeNewLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/user/$aclUserId': {
      id: '/_app/_wrapper/user/$aclUserId'
      path: '/$aclUserId'
      fullPath: '/user/$aclUserId'
      preLoaderRoute: typeof AppWrapperUserAclUserIdLazyImport
      parentRoute: typeof AppWrapperUserRouteImport
    }
    '/_app/_wrapper/user/new': {
      id: '/_app/_wrapper/user/new'
      path: '/new'
      fullPath: '/user/new'
      preLoaderRoute: typeof AppWrapperUserNewLazyImport
      parentRoute: typeof AppWrapperUserRouteImport
    }
    '/_app/_wrapper/vendor/$vendorId': {
      id: '/_app/_wrapper/vendor/$vendorId'
      path: '/vendor/$vendorId'
      fullPath: '/vendor/$vendorId'
      preLoaderRoute: typeof AppWrapperVendorVendorIdLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/vendor/new': {
      id: '/_app/_wrapper/vendor/new'
      path: '/vendor/new'
      fullPath: '/vendor/new'
      preLoaderRoute: typeof AppWrapperVendorNewLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/warehouse-inbound/$paymentRequestId': {
      id: '/_app/_wrapper/warehouse-inbound/$paymentRequestId'
      path: '/warehouse-inbound/$paymentRequestId'
      fullPath: '/warehouse-inbound/$paymentRequestId'
      preLoaderRoute: typeof AppWrapperWarehouseInboundPaymentRequestIdLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/customer/': {
      id: '/_app/_wrapper/customer/'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof AppWrapperCustomerIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/goods/': {
      id: '/_app/_wrapper/goods/'
      path: '/goods'
      fullPath: '/goods'
      preLoaderRoute: typeof AppWrapperGoodsIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/inventory-in/': {
      id: '/_app/_wrapper/inventory-in/'
      path: '/inventory-in'
      fullPath: '/inventory-in'
      preLoaderRoute: typeof AppWrapperInventoryInIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/inventory-out/': {
      id: '/_app/_wrapper/inventory-out/'
      path: '/inventory-out'
      fullPath: '/inventory-out'
      preLoaderRoute: typeof AppWrapperInventoryOutIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/inventory-stock/': {
      id: '/_app/_wrapper/inventory-stock/'
      path: '/inventory-stock'
      fullPath: '/inventory-stock'
      preLoaderRoute: typeof AppWrapperInventoryStockIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/notifications/': {
      id: '/_app/_wrapper/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppWrapperNotificationsIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/order/': {
      id: '/_app/_wrapper/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof AppWrapperOrderIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/payment/': {
      id: '/_app/_wrapper/payment/'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof AppWrapperPaymentIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/purchase/': {
      id: '/_app/_wrapper/purchase/'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof AppWrapperPurchaseIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/type/': {
      id: '/_app/_wrapper/type/'
      path: '/type'
      fullPath: '/type'
      preLoaderRoute: typeof AppWrapperTypeIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/user/': {
      id: '/_app/_wrapper/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof AppWrapperUserIndexLazyImport
      parentRoute: typeof AppWrapperUserRouteImport
    }
    '/_app/_wrapper/vendor/': {
      id: '/_app/_wrapper/vendor/'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AppWrapperVendorIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/warehouse-inbound/': {
      id: '/_app/_wrapper/warehouse-inbound/'
      path: '/warehouse-inbound'
      fullPath: '/warehouse-inbound'
      preLoaderRoute: typeof AppWrapperWarehouseInboundIndexLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
    '/_app/_wrapper/user/edit/$userId': {
      id: '/_app/_wrapper/user/edit/$userId'
      path: '/edit/$userId'
      fullPath: '/user/edit/$userId'
      preLoaderRoute: typeof AppWrapperUserEditUserIdLazyImport
      parentRoute: typeof AppWrapperUserRouteImport
    }
    '/_app/_wrapper/warehouse-inbound/receipt/$receiptId': {
      id: '/_app/_wrapper/warehouse-inbound/receipt/$receiptId'
      path: '/warehouse-inbound/receipt/$receiptId'
      fullPath: '/warehouse-inbound/receipt/$receiptId'
      preLoaderRoute: typeof AppWrapperWarehouseInboundReceiptReceiptIdLazyImport
      parentRoute: typeof AppWrapperRouteImport
    }
  }
}

// Create and export the route tree

interface AppWrapperUserRouteRouteChildren {
  AppWrapperUserAclUserIdLazyRoute: typeof AppWrapperUserAclUserIdLazyRoute
  AppWrapperUserNewLazyRoute: typeof AppWrapperUserNewLazyRoute
  AppWrapperUserIndexLazyRoute: typeof AppWrapperUserIndexLazyRoute
  AppWrapperUserEditUserIdLazyRoute: typeof AppWrapperUserEditUserIdLazyRoute
}

const AppWrapperUserRouteRouteChildren: AppWrapperUserRouteRouteChildren = {
  AppWrapperUserAclUserIdLazyRoute: AppWrapperUserAclUserIdLazyRoute,
  AppWrapperUserNewLazyRoute: AppWrapperUserNewLazyRoute,
  AppWrapperUserIndexLazyRoute: AppWrapperUserIndexLazyRoute,
  AppWrapperUserEditUserIdLazyRoute: AppWrapperUserEditUserIdLazyRoute,
}

const AppWrapperUserRouteRouteWithChildren =
  AppWrapperUserRouteRoute._addFileChildren(AppWrapperUserRouteRouteChildren)

interface AppWrapperRouteRouteChildren {
  AppWrapperUserRouteRoute: typeof AppWrapperUserRouteRouteWithChildren
  AppWrapperCustomerCustomerIdLazyRoute: typeof AppWrapperCustomerCustomerIdLazyRoute
  AppWrapperCustomerNewLazyRoute: typeof AppWrapperCustomerNewLazyRoute
  AppWrapperGoodsGoodsIdLazyRoute: typeof AppWrapperGoodsGoodsIdLazyRoute
  AppWrapperGoodsNewLazyRoute: typeof AppWrapperGoodsNewLazyRoute
  AppWrapperInventoryInInventoryCodeLazyRoute: typeof AppWrapperInventoryInInventoryCodeLazyRoute
  AppWrapperOrderOrderIdLazyRoute: typeof AppWrapperOrderOrderIdLazyRoute
  AppWrapperOrderNewLazyRoute: typeof AppWrapperOrderNewLazyRoute
  AppWrapperPaymentPaymentIdLazyRoute: typeof AppWrapperPaymentPaymentIdLazyRoute
  AppWrapperPaymentNewLazyRoute: typeof AppWrapperPaymentNewLazyRoute
  AppWrapperPurchasePurchaseIdLazyRoute: typeof AppWrapperPurchasePurchaseIdLazyRoute
  AppWrapperPurchaseNewLazyRoute: typeof AppWrapperPurchaseNewLazyRoute
  AppWrapperTypeTypeIdLazyRoute: typeof AppWrapperTypeTypeIdLazyRoute
  AppWrapperTypeNewLazyRoute: typeof AppWrapperTypeNewLazyRoute
  AppWrapperVendorVendorIdLazyRoute: typeof AppWrapperVendorVendorIdLazyRoute
  AppWrapperVendorNewLazyRoute: typeof AppWrapperVendorNewLazyRoute
  AppWrapperWarehouseInboundPaymentRequestIdLazyRoute: typeof AppWrapperWarehouseInboundPaymentRequestIdLazyRoute
  AppWrapperCustomerIndexLazyRoute: typeof AppWrapperCustomerIndexLazyRoute
  AppWrapperGoodsIndexLazyRoute: typeof AppWrapperGoodsIndexLazyRoute
  AppWrapperInventoryInIndexLazyRoute: typeof AppWrapperInventoryInIndexLazyRoute
  AppWrapperInventoryOutIndexLazyRoute: typeof AppWrapperInventoryOutIndexLazyRoute
  AppWrapperInventoryStockIndexLazyRoute: typeof AppWrapperInventoryStockIndexLazyRoute
  AppWrapperNotificationsIndexLazyRoute: typeof AppWrapperNotificationsIndexLazyRoute
  AppWrapperOrderIndexLazyRoute: typeof AppWrapperOrderIndexLazyRoute
  AppWrapperPaymentIndexLazyRoute: typeof AppWrapperPaymentIndexLazyRoute
  AppWrapperPurchaseIndexLazyRoute: typeof AppWrapperPurchaseIndexLazyRoute
  AppWrapperTypeIndexLazyRoute: typeof AppWrapperTypeIndexLazyRoute
  AppWrapperVendorIndexLazyRoute: typeof AppWrapperVendorIndexLazyRoute
  AppWrapperWarehouseInboundIndexLazyRoute: typeof AppWrapperWarehouseInboundIndexLazyRoute
  AppWrapperWarehouseInboundReceiptReceiptIdLazyRoute: typeof AppWrapperWarehouseInboundReceiptReceiptIdLazyRoute
}

const AppWrapperRouteRouteChildren: AppWrapperRouteRouteChildren = {
  AppWrapperUserRouteRoute: AppWrapperUserRouteRouteWithChildren,
  AppWrapperCustomerCustomerIdLazyRoute: AppWrapperCustomerCustomerIdLazyRoute,
  AppWrapperCustomerNewLazyRoute: AppWrapperCustomerNewLazyRoute,
  AppWrapperGoodsGoodsIdLazyRoute: AppWrapperGoodsGoodsIdLazyRoute,
  AppWrapperGoodsNewLazyRoute: AppWrapperGoodsNewLazyRoute,
  AppWrapperInventoryInInventoryCodeLazyRoute:
    AppWrapperInventoryInInventoryCodeLazyRoute,
  AppWrapperOrderOrderIdLazyRoute: AppWrapperOrderOrderIdLazyRoute,
  AppWrapperOrderNewLazyRoute: AppWrapperOrderNewLazyRoute,
  AppWrapperPaymentPaymentIdLazyRoute: AppWrapperPaymentPaymentIdLazyRoute,
  AppWrapperPaymentNewLazyRoute: AppWrapperPaymentNewLazyRoute,
  AppWrapperPurchasePurchaseIdLazyRoute: AppWrapperPurchasePurchaseIdLazyRoute,
  AppWrapperPurchaseNewLazyRoute: AppWrapperPurchaseNewLazyRoute,
  AppWrapperTypeTypeIdLazyRoute: AppWrapperTypeTypeIdLazyRoute,
  AppWrapperTypeNewLazyRoute: AppWrapperTypeNewLazyRoute,
  AppWrapperVendorVendorIdLazyRoute: AppWrapperVendorVendorIdLazyRoute,
  AppWrapperVendorNewLazyRoute: AppWrapperVendorNewLazyRoute,
  AppWrapperWarehouseInboundPaymentRequestIdLazyRoute:
    AppWrapperWarehouseInboundPaymentRequestIdLazyRoute,
  AppWrapperCustomerIndexLazyRoute: AppWrapperCustomerIndexLazyRoute,
  AppWrapperGoodsIndexLazyRoute: AppWrapperGoodsIndexLazyRoute,
  AppWrapperInventoryInIndexLazyRoute: AppWrapperInventoryInIndexLazyRoute,
  AppWrapperInventoryOutIndexLazyRoute: AppWrapperInventoryOutIndexLazyRoute,
  AppWrapperInventoryStockIndexLazyRoute:
    AppWrapperInventoryStockIndexLazyRoute,
  AppWrapperNotificationsIndexLazyRoute: AppWrapperNotificationsIndexLazyRoute,
  AppWrapperOrderIndexLazyRoute: AppWrapperOrderIndexLazyRoute,
  AppWrapperPaymentIndexLazyRoute: AppWrapperPaymentIndexLazyRoute,
  AppWrapperPurchaseIndexLazyRoute: AppWrapperPurchaseIndexLazyRoute,
  AppWrapperTypeIndexLazyRoute: AppWrapperTypeIndexLazyRoute,
  AppWrapperVendorIndexLazyRoute: AppWrapperVendorIndexLazyRoute,
  AppWrapperWarehouseInboundIndexLazyRoute:
    AppWrapperWarehouseInboundIndexLazyRoute,
  AppWrapperWarehouseInboundReceiptReceiptIdLazyRoute:
    AppWrapperWarehouseInboundReceiptReceiptIdLazyRoute,
}

const AppWrapperRouteRouteWithChildren = AppWrapperRouteRoute._addFileChildren(
  AppWrapperRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '': typeof AppWrapperRouteRouteWithChildren
  '/home': typeof AppHomeRoute
  '/login': typeof AuthLoginRoute
  '/contract': typeof AppContractLazyRoute
  '/setting': typeof AppSettingLazyRoute
  '/user': typeof AppWrapperUserRouteRouteWithChildren
  '/customer/$customerId': typeof AppWrapperCustomerCustomerIdLazyRoute
  '/customer/new': typeof AppWrapperCustomerNewLazyRoute
  '/goods/$goodsId': typeof AppWrapperGoodsGoodsIdLazyRoute
  '/goods/new': typeof AppWrapperGoodsNewLazyRoute
  '/inventory-in/$inventoryCode': typeof AppWrapperInventoryInInventoryCodeLazyRoute
  '/order/$orderId': typeof AppWrapperOrderOrderIdLazyRoute
  '/order/new': typeof AppWrapperOrderNewLazyRoute
  '/payment/$paymentId': typeof AppWrapperPaymentPaymentIdLazyRoute
  '/payment/new': typeof AppWrapperPaymentNewLazyRoute
  '/purchase/$purchaseId': typeof AppWrapperPurchasePurchaseIdLazyRoute
  '/purchase/new': typeof AppWrapperPurchaseNewLazyRoute
  '/type/$typeId': typeof AppWrapperTypeTypeIdLazyRoute
  '/type/new': typeof AppWrapperTypeNewLazyRoute
  '/user/$aclUserId': typeof AppWrapperUserAclUserIdLazyRoute
  '/user/new': typeof AppWrapperUserNewLazyRoute
  '/vendor/$vendorId': typeof AppWrapperVendorVendorIdLazyRoute
  '/vendor/new': typeof AppWrapperVendorNewLazyRoute
  '/warehouse-inbound/$paymentRequestId': typeof AppWrapperWarehouseInboundPaymentRequestIdLazyRoute
  '/customer': typeof AppWrapperCustomerIndexLazyRoute
  '/goods': typeof AppWrapperGoodsIndexLazyRoute
  '/inventory-in': typeof AppWrapperInventoryInIndexLazyRoute
  '/inventory-out': typeof AppWrapperInventoryOutIndexLazyRoute
  '/inventory-stock': typeof AppWrapperInventoryStockIndexLazyRoute
  '/notifications': typeof AppWrapperNotificationsIndexLazyRoute
  '/order': typeof AppWrapperOrderIndexLazyRoute
  '/payment': typeof AppWrapperPaymentIndexLazyRoute
  '/purchase': typeof AppWrapperPurchaseIndexLazyRoute
  '/type': typeof AppWrapperTypeIndexLazyRoute
  '/user/': typeof AppWrapperUserIndexLazyRoute
  '/vendor': typeof AppWrapperVendorIndexLazyRoute
  '/warehouse-inbound': typeof AppWrapperWarehouseInboundIndexLazyRoute
  '/user/edit/$userId': typeof AppWrapperUserEditUserIdLazyRoute
  '/warehouse-inbound/receipt/$receiptId': typeof AppWrapperWarehouseInboundReceiptReceiptIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '': typeof AppWrapperRouteRouteWithChildren
  '/home': typeof AppHomeRoute
  '/login': typeof AuthLoginRoute
  '/contract': typeof AppContractLazyRoute
  '/setting': typeof AppSettingLazyRoute
  '/customer/$customerId': typeof AppWrapperCustomerCustomerIdLazyRoute
  '/customer/new': typeof AppWrapperCustomerNewLazyRoute
  '/goods/$goodsId': typeof AppWrapperGoodsGoodsIdLazyRoute
  '/goods/new': typeof AppWrapperGoodsNewLazyRoute
  '/inventory-in/$inventoryCode': typeof AppWrapperInventoryInInventoryCodeLazyRoute
  '/order/$orderId': typeof AppWrapperOrderOrderIdLazyRoute
  '/order/new': typeof AppWrapperOrderNewLazyRoute
  '/payment/$paymentId': typeof AppWrapperPaymentPaymentIdLazyRoute
  '/payment/new': typeof AppWrapperPaymentNewLazyRoute
  '/purchase/$purchaseId': typeof AppWrapperPurchasePurchaseIdLazyRoute
  '/purchase/new': typeof AppWrapperPurchaseNewLazyRoute
  '/type/$typeId': typeof AppWrapperTypeTypeIdLazyRoute
  '/type/new': typeof AppWrapperTypeNewLazyRoute
  '/user/$aclUserId': typeof AppWrapperUserAclUserIdLazyRoute
  '/user/new': typeof AppWrapperUserNewLazyRoute
  '/vendor/$vendorId': typeof AppWrapperVendorVendorIdLazyRoute
  '/vendor/new': typeof AppWrapperVendorNewLazyRoute
  '/warehouse-inbound/$paymentRequestId': typeof AppWrapperWarehouseInboundPaymentRequestIdLazyRoute
  '/customer': typeof AppWrapperCustomerIndexLazyRoute
  '/goods': typeof AppWrapperGoodsIndexLazyRoute
  '/inventory-in': typeof AppWrapperInventoryInIndexLazyRoute
  '/inventory-out': typeof AppWrapperInventoryOutIndexLazyRoute
  '/inventory-stock': typeof AppWrapperInventoryStockIndexLazyRoute
  '/notifications': typeof AppWrapperNotificationsIndexLazyRoute
  '/order': typeof AppWrapperOrderIndexLazyRoute
  '/payment': typeof AppWrapperPaymentIndexLazyRoute
  '/purchase': typeof AppWrapperPurchaseIndexLazyRoute
  '/type': typeof AppWrapperTypeIndexLazyRoute
  '/user': typeof AppWrapperUserIndexLazyRoute
  '/vendor': typeof AppWrapperVendorIndexLazyRoute
  '/warehouse-inbound': typeof AppWrapperWarehouseInboundIndexLazyRoute
  '/user/edit/$userId': typeof AppWrapperUserEditUserIdLazyRoute
  '/warehouse-inbound/receipt/$receiptId': typeof AppWrapperWarehouseInboundReceiptReceiptIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_app/_wrapper': typeof AppWrapperRouteRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/contract': typeof AppContractLazyRoute
  '/_app/setting': typeof AppSettingLazyRoute
  '/_app/_wrapper/user': typeof AppWrapperUserRouteRouteWithChildren
  '/_app/_wrapper/customer/$customerId': typeof AppWrapperCustomerCustomerIdLazyRoute
  '/_app/_wrapper/customer/new': typeof AppWrapperCustomerNewLazyRoute
  '/_app/_wrapper/goods/$goodsId': typeof AppWrapperGoodsGoodsIdLazyRoute
  '/_app/_wrapper/goods/new': typeof AppWrapperGoodsNewLazyRoute
  '/_app/_wrapper/inventory-in/$inventoryCode': typeof AppWrapperInventoryInInventoryCodeLazyRoute
  '/_app/_wrapper/order/$orderId': typeof AppWrapperOrderOrderIdLazyRoute
  '/_app/_wrapper/order/new': typeof AppWrapperOrderNewLazyRoute
  '/_app/_wrapper/payment/$paymentId': typeof AppWrapperPaymentPaymentIdLazyRoute
  '/_app/_wrapper/payment/new': typeof AppWrapperPaymentNewLazyRoute
  '/_app/_wrapper/purchase/$purchaseId': typeof AppWrapperPurchasePurchaseIdLazyRoute
  '/_app/_wrapper/purchase/new': typeof AppWrapperPurchaseNewLazyRoute
  '/_app/_wrapper/type/$typeId': typeof AppWrapperTypeTypeIdLazyRoute
  '/_app/_wrapper/type/new': typeof AppWrapperTypeNewLazyRoute
  '/_app/_wrapper/user/$aclUserId': typeof AppWrapperUserAclUserIdLazyRoute
  '/_app/_wrapper/user/new': typeof AppWrapperUserNewLazyRoute
  '/_app/_wrapper/vendor/$vendorId': typeof AppWrapperVendorVendorIdLazyRoute
  '/_app/_wrapper/vendor/new': typeof AppWrapperVendorNewLazyRoute
  '/_app/_wrapper/warehouse-inbound/$paymentRequestId': typeof AppWrapperWarehouseInboundPaymentRequestIdLazyRoute
  '/_app/_wrapper/customer/': typeof AppWrapperCustomerIndexLazyRoute
  '/_app/_wrapper/goods/': typeof AppWrapperGoodsIndexLazyRoute
  '/_app/_wrapper/inventory-in/': typeof AppWrapperInventoryInIndexLazyRoute
  '/_app/_wrapper/inventory-out/': typeof AppWrapperInventoryOutIndexLazyRoute
  '/_app/_wrapper/inventory-stock/': typeof AppWrapperInventoryStockIndexLazyRoute
  '/_app/_wrapper/notifications/': typeof AppWrapperNotificationsIndexLazyRoute
  '/_app/_wrapper/order/': typeof AppWrapperOrderIndexLazyRoute
  '/_app/_wrapper/payment/': typeof AppWrapperPaymentIndexLazyRoute
  '/_app/_wrapper/purchase/': typeof AppWrapperPurchaseIndexLazyRoute
  '/_app/_wrapper/type/': typeof AppWrapperTypeIndexLazyRoute
  '/_app/_wrapper/user/': typeof AppWrapperUserIndexLazyRoute
  '/_app/_wrapper/vendor/': typeof AppWrapperVendorIndexLazyRoute
  '/_app/_wrapper/warehouse-inbound/': typeof AppWrapperWarehouseInboundIndexLazyRoute
  '/_app/_wrapper/user/edit/$userId': typeof AppWrapperUserEditUserIdLazyRoute
  '/_app/_wrapper/warehouse-inbound/receipt/$receiptId': typeof AppWrapperWarehouseInboundReceiptReceiptIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | ''
    | '/home'
    | '/login'
    | '/contract'
    | '/setting'
    | '/user'
    | '/customer/$customerId'
    | '/customer/new'
    | '/goods/$goodsId'
    | '/goods/new'
    | '/inventory-in/$inventoryCode'
    | '/order/$orderId'
    | '/order/new'
    | '/payment/$paymentId'
    | '/payment/new'
    | '/purchase/$purchaseId'
    | '/purchase/new'
    | '/type/$typeId'
    | '/type/new'
    | '/user/$aclUserId'
    | '/user/new'
    | '/vendor/$vendorId'
    | '/vendor/new'
    | '/warehouse-inbound/$paymentRequestId'
    | '/customer'
    | '/goods'
    | '/inventory-in'
    | '/inventory-out'
    | '/inventory-stock'
    | '/notifications'
    | '/order'
    | '/payment'
    | '/purchase'
    | '/type'
    | '/user/'
    | '/vendor'
    | '/warehouse-inbound'
    | '/user/edit/$userId'
    | '/warehouse-inbound/receipt/$receiptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | ''
    | '/home'
    | '/login'
    | '/contract'
    | '/setting'
    | '/customer/$customerId'
    | '/customer/new'
    | '/goods/$goodsId'
    | '/goods/new'
    | '/inventory-in/$inventoryCode'
    | '/order/$orderId'
    | '/order/new'
    | '/payment/$paymentId'
    | '/payment/new'
    | '/purchase/$purchaseId'
    | '/purchase/new'
    | '/type/$typeId'
    | '/type/new'
    | '/user/$aclUserId'
    | '/user/new'
    | '/vendor/$vendorId'
    | '/vendor/new'
    | '/warehouse-inbound/$paymentRequestId'
    | '/customer'
    | '/goods'
    | '/inventory-in'
    | '/inventory-out'
    | '/inventory-stock'
    | '/notifications'
    | '/order'
    | '/payment'
    | '/purchase'
    | '/type'
    | '/user'
    | '/vendor'
    | '/warehouse-inbound'
    | '/user/edit/$userId'
    | '/warehouse-inbound/receipt/$receiptId'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/_app/_wrapper'
    | '/_app/home'
    | '/_auth/login'
    | '/_app/contract'
    | '/_app/setting'
    | '/_app/_wrapper/user'
    | '/_app/_wrapper/customer/$customerId'
    | '/_app/_wrapper/customer/new'
    | '/_app/_wrapper/goods/$goodsId'
    | '/_app/_wrapper/goods/new'
    | '/_app/_wrapper/inventory-in/$inventoryCode'
    | '/_app/_wrapper/order/$orderId'
    | '/_app/_wrapper/order/new'
    | '/_app/_wrapper/payment/$paymentId'
    | '/_app/_wrapper/payment/new'
    | '/_app/_wrapper/purchase/$purchaseId'
    | '/_app/_wrapper/purchase/new'
    | '/_app/_wrapper/type/$typeId'
    | '/_app/_wrapper/type/new'
    | '/_app/_wrapper/user/$aclUserId'
    | '/_app/_wrapper/user/new'
    | '/_app/_wrapper/vendor/$vendorId'
    | '/_app/_wrapper/vendor/new'
    | '/_app/_wrapper/warehouse-inbound/$paymentRequestId'
    | '/_app/_wrapper/customer/'
    | '/_app/_wrapper/goods/'
    | '/_app/_wrapper/inventory-in/'
    | '/_app/_wrapper/inventory-out/'
    | '/_app/_wrapper/inventory-stock/'
    | '/_app/_wrapper/notifications/'
    | '/_app/_wrapper/order/'
    | '/_app/_wrapper/payment/'
    | '/_app/_wrapper/purchase/'
    | '/_app/_wrapper/type/'
    | '/_app/_wrapper/user/'
    | '/_app/_wrapper/vendor/'
    | '/_app/_wrapper/warehouse-inbound/'
    | '/_app/_wrapper/user/edit/$userId'
    | '/_app/_wrapper/warehouse-inbound/receipt/$receiptId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AppWrapperRouteRoute: typeof AppWrapperRouteRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AppContractLazyRoute: typeof AppContractLazyRoute
  AppSettingLazyRoute: typeof AppSettingLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AppWrapperRouteRoute: AppWrapperRouteRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AuthLoginRoute: AuthLoginRoute,
  AppContractLazyRoute: AppContractLazyRoute,
  AppSettingLazyRoute: AppSettingLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/404",
        "/_app/_wrapper",
        "/_app/home",
        "/_auth/login",
        "/_app/contract",
        "/_app/setting"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/404": {
      "filePath": "404.tsx"
    },
    "/_app/_wrapper": {
      "filePath": "_app/_wrapper/route.tsx",
      "children": [
        "/_app/_wrapper/user",
        "/_app/_wrapper/customer/$customerId",
        "/_app/_wrapper/customer/new",
        "/_app/_wrapper/goods/$goodsId",
        "/_app/_wrapper/goods/new",
        "/_app/_wrapper/inventory-in/$inventoryCode",
        "/_app/_wrapper/order/$orderId",
        "/_app/_wrapper/order/new",
        "/_app/_wrapper/payment/$paymentId",
        "/_app/_wrapper/payment/new",
        "/_app/_wrapper/purchase/$purchaseId",
        "/_app/_wrapper/purchase/new",
        "/_app/_wrapper/type/$typeId",
        "/_app/_wrapper/type/new",
        "/_app/_wrapper/vendor/$vendorId",
        "/_app/_wrapper/vendor/new",
        "/_app/_wrapper/warehouse-inbound/$paymentRequestId",
        "/_app/_wrapper/customer/",
        "/_app/_wrapper/goods/",
        "/_app/_wrapper/inventory-in/",
        "/_app/_wrapper/inventory-out/",
        "/_app/_wrapper/inventory-stock/",
        "/_app/_wrapper/notifications/",
        "/_app/_wrapper/order/",
        "/_app/_wrapper/payment/",
        "/_app/_wrapper/purchase/",
        "/_app/_wrapper/type/",
        "/_app/_wrapper/vendor/",
        "/_app/_wrapper/warehouse-inbound/",
        "/_app/_wrapper/warehouse-inbound/receipt/$receiptId"
      ]
    },
    "/_app/home": {
      "filePath": "_app/home.tsx"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx"
    },
    "/_app/contract": {
      "filePath": "_app/contract.lazy.tsx"
    },
    "/_app/setting": {
      "filePath": "_app/setting.lazy.tsx"
    },
    "/_app/_wrapper/user": {
      "filePath": "_app/_wrapper/user/route.tsx",
      "parent": "/_app/_wrapper",
      "children": [
        "/_app/_wrapper/user/$aclUserId",
        "/_app/_wrapper/user/new",
        "/_app/_wrapper/user/",
        "/_app/_wrapper/user/edit/$userId"
      ]
    },
    "/_app/_wrapper/customer/$customerId": {
      "filePath": "_app/_wrapper/customer/$customerId.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/customer/new": {
      "filePath": "_app/_wrapper/customer/new.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/goods/$goodsId": {
      "filePath": "_app/_wrapper/goods/$goodsId.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/goods/new": {
      "filePath": "_app/_wrapper/goods/new.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/inventory-in/$inventoryCode": {
      "filePath": "_app/_wrapper/inventory-in/$inventoryCode.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/order/$orderId": {
      "filePath": "_app/_wrapper/order/$orderId.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/order/new": {
      "filePath": "_app/_wrapper/order/new.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/payment/$paymentId": {
      "filePath": "_app/_wrapper/payment/$paymentId.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/payment/new": {
      "filePath": "_app/_wrapper/payment/new.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/purchase/$purchaseId": {
      "filePath": "_app/_wrapper/purchase/$purchaseId.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/purchase/new": {
      "filePath": "_app/_wrapper/purchase/new.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/type/$typeId": {
      "filePath": "_app/_wrapper/type/$typeId.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/type/new": {
      "filePath": "_app/_wrapper/type/new.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/user/$aclUserId": {
      "filePath": "_app/_wrapper/user/$aclUserId.lazy.tsx",
      "parent": "/_app/_wrapper/user"
    },
    "/_app/_wrapper/user/new": {
      "filePath": "_app/_wrapper/user/new.lazy.tsx",
      "parent": "/_app/_wrapper/user"
    },
    "/_app/_wrapper/vendor/$vendorId": {
      "filePath": "_app/_wrapper/vendor/$vendorId.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/vendor/new": {
      "filePath": "_app/_wrapper/vendor/new.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/warehouse-inbound/$paymentRequestId": {
      "filePath": "_app/_wrapper/warehouse-inbound/$paymentRequestId.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/customer/": {
      "filePath": "_app/_wrapper/customer/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/goods/": {
      "filePath": "_app/_wrapper/goods/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/inventory-in/": {
      "filePath": "_app/_wrapper/inventory-in/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/inventory-out/": {
      "filePath": "_app/_wrapper/inventory-out/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/inventory-stock/": {
      "filePath": "_app/_wrapper/inventory-stock/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/notifications/": {
      "filePath": "_app/_wrapper/notifications/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/order/": {
      "filePath": "_app/_wrapper/order/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/payment/": {
      "filePath": "_app/_wrapper/payment/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/purchase/": {
      "filePath": "_app/_wrapper/purchase/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/type/": {
      "filePath": "_app/_wrapper/type/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/user/": {
      "filePath": "_app/_wrapper/user/index.lazy.tsx",
      "parent": "/_app/_wrapper/user"
    },
    "/_app/_wrapper/vendor/": {
      "filePath": "_app/_wrapper/vendor/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/warehouse-inbound/": {
      "filePath": "_app/_wrapper/warehouse-inbound/index.lazy.tsx",
      "parent": "/_app/_wrapper"
    },
    "/_app/_wrapper/user/edit/$userId": {
      "filePath": "_app/_wrapper/user/edit.$userId.lazy.tsx",
      "parent": "/_app/_wrapper/user"
    },
    "/_app/_wrapper/warehouse-inbound/receipt/$receiptId": {
      "filePath": "_app/_wrapper/warehouse-inbound/receipt.$receiptId.lazy.tsx",
      "parent": "/_app/_wrapper"
    }
  }
}
ROUTE_MANIFEST_END */
